name: GitFlow CI

on: 
  pull_request_review:
    branches: [main, development]

jobs:
  build:
    runs-on: ubuntu-latest
    name: GitFlow CI
    steps:
      - uses: actions/checkout@v2
      - name: Run git flow process
        uses: mlucascardoso/git-flow-ci-cd-action@1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          master_branch: 'main'
          development_branch: 'development'